### ISSUE TITLE
Daily summary contains each day old activities on files not visible by the recipient

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/activity#1089] opened 2023-02-22 16:09 UTC
### Steps to reproduce
1. Enable daily activity summary
2. Examine mails sent for a couple of days
3. See unrelated activities on files you shouldn't even know the existence

### Expected behaviour
Daily Summary should only send relevant activity on files that user own or shared to him

### Actual behaviour
User can see old activity on files not visible

### Server configuration

**Operating system**:
Debian 11
**Web server:**
Apache
**Database:**
Maria DB
**PHP version:**
8.1
**Nextcloud version:** (see Nextcloud admin page)
25.0.3

**List of activated apps:**

```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.7.2
  - announcementcenter: 6.5.0
  - approval: 1.0.12
  - calendar: 4.2.3
  - cfg_share_links: 3.0.2
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - drawio: 2.1.0
  - emlviewer: 1.0.7
  - event_update_notification: 2.0.0
  - external: 5.0.2
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_archive: 1.1.2
  - files_automatedtagging: 1.15.2
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_linkeditor: 1.1.13
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - forms: 3.1.0
  - groupfolders: 13.1.1
  - impersonate: 1.11.0
  - issuetemplate: 0.7.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.3
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.2
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.2
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - smb_test: 0.3.5
  - snappymail: 2.26.3
  - spreed: 15.0.3
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - auto_groups: 1.4.1
  - bruteforcesettings: 2.2.0
  - calendar_resource_management: 0.1.0
  - customproperties: 2.0.4
  - encryption
  - files_markdown: 2.3.6
  - firstrunwizard: 2.12.0
  - group_everyone: 0.1.10
  - pdfdraw
  - privacy: 1.7.0
  - recommendations: 1.3.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login
  - tables: 0.2.1
  - workflow_script: 1.8.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "simpleSignUpLink.shown": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agglo-montbeliard.fr",
            "192.168.50.106",
            "192.168.50.106"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.agglo-montbeliard.fr\/",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 15",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "default_phone_region": "FR",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "spreed",
            "files_mindmap",
            "pdfdraw",
            "issuetemplate",
            "files_linkeditor",
            "files_texteditor",
            "files_trackdownloads",
            "emlviewer",
            "files_archive",
            "impersonate",
            "extract"
        ],
        "allow_local_remote_servers": true,
        "default_language": "fr",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_memory": 512,
        "app.mail.verify-tls-peer": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "sharing.enable_share_mail": false
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration
**Browser:**
Firefox 102.6 ESR
**Operating system:**
Windows 10
#### Nextcloud log (data/nextcloud.log)
```
not relevant
```

#### Browser log
```
not relevant
```

Here is daily summary mail for today and yesterday :

![image](https://user-images.githubusercontent.com/6248852/220685014-3c87e89c-0040-4381-894a-c812c130ac87.png)

The same old non relevant files are sent each day : 

![image](https://user-images.githubusercontent.com/6248852/220684105-093dba44-8198-45bc-962d-df80933078f8.png)

**Comment by kottonau** [comment] 2023-05-04 07:19
We have the same issue with the latest version of the 26 branch. Did you find any solution @Mer0me?

**Comment by Mer0me** [comment] 2023-05-04 08:28
No solution, but I suspect a "Group Folders" app bug. The shared files listed in the mail are from a group folder.
@kottonau : Do you have Group Folder App enabled too ?

**Comment by kottonau** [comment] 2023-05-04 08:48
Yes, we are using [Group Folders.](https://apps.nextcloud.com/apps/groupfolders). However, I stumbled over this issue because of the problem with old activities. And the summary shows old activities regarding files and deck cards too. Today's summary:
![image](https://user-images.githubusercontent.com/78583605/236155014-3e3c31f9-5917-4ef8-b6c1-bb16ed298381.png)

I have to check with my colleagues regarding the other issue (activities on files which are not shared to this specific user).

**Comment by kottonau** [comment] 2023-05-04 08:54
Did a little more digging as for the permission issue:

Probably related: https://github.com/nextcloud/groupfolders/issues/1057
See warning box: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/activity_configuration.html

**Comment by joshtrichards** [comment] 2024-08-07 01:26
Duplicate of nextcloud/groupfolders#1057

**Closed by joshtrichards** 2024-08-07 01:26 UTC
Labels: bug
