### ISSUE TITLE
Activity emails or emails about Unhandled notifications are never sent

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [nextcloud/activity#1190] opened 2023-05-25 07:51 UTC
### Steps to reproduce
1. Install NextCloud server
2. Enable all Activity emails as shown in the screenshot bellow
3. Wait to receive email notifications without success

### Expected behaviour
I wish that my Nextcloud users receive emails about notifications regarding their files.
Hence, I've enabled the notifications as shown in the next screenshot. None of them seem to be working however. 
I don't receive Activity emails `as soon as possible` and I definitely do not receive `Email reminders about unhandled notifications after 1 hour`. 
The only email I think I am actually receiving, is the `Daily activity summary` and I don't even receive it in the morning,..
The weirdest part is that I receive test emails or other notifications, e.g. password change, but not Activity related ones.

From my research I realize that this is a known issue and it's really frustrating since there are no answers or solutions.
No one seems to be caring about this core functionality.

![image](https://github.com/nextcloud/activity/assets/13638976/0a6d1a1a-f82b-412f-8969-5682958f1a3d)

### Actual behaviour
Activity emails not working.

### Server configuration
**Nextcloud version:** 26.0.1
**PHP version:** 8.2
**Database:**  mariadb:10.6

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'nextcloud-redis',
    'password' => 'mypass',
    'port' => 6379,
  ),
  'instanceid' => 'ocq4pg6jocqr',
  'passwordsalt' => 'passsalo',
  'secret' => 'secret+n',
  'trusted_domains' => 
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '26.0.1.1',
  'overwrite.cli.url' => 'http://example.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'mypass',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'documentserver_community',
  ),
  'mail_from_address' => 'from-address',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'domain.com',
  'mail_smtphost' => 'server.domain.com',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => '60',
  'enforce_theme' => 'breezedark',
  'skeletondirectory' => '',
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
);
```

**Where did you install Nextcloud from:** I installed nextcloud via docker-compose. I can provide it if needed.

---
Under logging, I can see the following Errors each time the cronjob is executed, however I am unsure what they mean or if they are related to my issue.
![image](https://github.com/nextcloud/activity/assets/13638976/8d45ab72-7491-4f92-bc53-1f95af08c42c)

I've been stuck with the notifications problem for weeks now. Any help is kindly appreciated.

Thank you

**Comment by woojunrt** [comment] 2023-05-29 01:17
The same issue as above, can`t sent mail.
its appreaciated that who can handle this.

**Comment by sunshine7x** [comment] 2023-06-12 17:56
Same thing here.

**Comment by joshtrichards** [comment] 2023-07-05 16:10
@woojunrt Similar behavior or the exact same error in your Nextcloud log?

@sunshine7x  Similar behavior or the exact same error in your Nextcloud log?

**Comment by joshtrichards** [comment] 2024-08-07 21:21
Duplicate of nextcloud/approval#29

**Closed by joshtrichards** 2024-08-07 21:21 UTC
