### ISSUE TITLE
Dozens of notifications after viewing a video shared via public link

### ISSUE THREAD

**Issue by jwojtas10** [nextcloud/activity#1737] opened 2024-07-24 09:15 UTC
I receive dozens of notifications after viewing a video from public link.

### Steps to reproduce
1. Upload .MOV file to folder
2. Share folder via public link
3. View the video from public link
4. Now you have dozens of notifications.

### Expected behaviour
The viewing of video won't cause dozens of notifications.

### Actual behaviour
After viewing the video I receive dozens of notifications "blabla.MOV downloaded via public link." even if I don't download it. 
![image](https://github.com/user-attachments/assets/0e3b0ef8-4776-46e9-9381-f4a20627d34b)

**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
Postgresql
**PHP version:**
8.1.2
**Nextcloud version:** (see Nextcloud admin page)
29.0.4

**Comment by joshtrichards** [comment] 2024-09-15 21:44
Duplicate of nextcloud/server#36875

**Closed by joshtrichards** 2024-09-15 21:44 UTC
Labels: bug, feature: implementations
