### ISSUE TITLE
[BITV]: Adapt visual "Your activities" `<h1>` which remains the same through all activities pages 

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/activity#1464] opened 2023-12-15 08:35 UTC
"your activities" is always visible as `<h1>`. Some time ago i've implemented visually hidden `<h1>` to be relied on the section in a sidebar: https://github.com/nextcloud/activity/pull/1081

@nickvergessen is it a bug or a feature?

**Comment by nickvergessen** [comment] 2023-12-15 08:44
I'm not up to date with the recent changes the app is going through in the frontend,
but looks intentional:
https://github.com/nextcloud/activity/blame/2accba255dcd732bf08bdfe51efbd087b49b7af8/src/views/ActivityAppFeed.vue#L24

**Comment by susnux** [comment] 2024-01-09 10:48
This was decided by designers also for photos and logreader

**Comment by JuliaKirschenheuter** [comment] 2024-01-12 09:46
Dear designers,

In our other apps like Files, Photos `<h1>` visual heading (or hidden heading) changes are based on a section in left navigation (like "Shared with you", "Collaborative albums"). This is also important for a11y. Could we adapt it for Activity too? Then we would have instead of "Your activities" -> "By others".

**Comment by jancborchardt** [comment] 2024-01-12 13:07
Seems like a duplicate of this issue I reported 1 day before this one? :D
https://github.com/nextcloud/activity/issues/1463

And as far as I understand @JuliaKirschenheuter I agree with your take?

**Comment by JuliaKirschenheuter** [comment] 2024-01-12 13:10
Thank you @jancborchardt!

**Closed** 2024-01-16 09:52 UTC
Labels: 1. to develop, accessibility
