### ISSUE TITLE
Feature Request: More filters (Time-Range, User, Operation)

### ISSUE THREAD

**Issue by muckinger** [nextcloud/activity#288] opened 2018-08-17 16:37 UTC
To better filter the very long Activity Log, we need to have more filters. Best would be additionally:

- Filter by a Time-Span (From-To)
- As Admin: Filter by a User
- Filter by Action (deleted, created, changed, renamed...)

Would  be great if this can be a new Feature. Didn't find a request for this.

Thx.

**Comment by ccoenen** [comment] 2018-12-11 21:44
This is similar to #71. That ticket is already tagged, so I'll pile on there :-)

**Comment by nickvergessen** [comment] 2020-03-10 12:12
Duplicate of #71

**Closed by nickvergessen** 2020-03-10 12:12 UTC
