### ISSUE TITLE
Activites stream does not load `userLocal` is undefined

### ISSUE THREAD

**Issue by susnux** [nextcloud/activity#1240] opened 2023-07-01 19:48 UTC
### Steps to reproduce
1. Install current master version
2. Let another user share a file with you
3. Go to the activity app (`/apps/activity/`)

### Expected behaviour
Activities load and are displayed + no error.

### Actual behaviour
Infinite loading + console error:

```
richObjectStringParser.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'userLocal')
    at Object.parseParameter (richObjectStringParser.js:1:1076)
    at richObjectStringParser.js:1:278
    at Function.Ge (each.js:14:7)
    at Object.parseMessage (richObjectStringParser.js:1:192)
    at Object.addActivity (script.js:1:4262)
    at Object.appendActivityToContainer (script.js:1:3435)
    at Object.handleActivitiesCallback (script.js:1:2755)
    at Object.success (script.js:1:2330)
    at l (jquery.js:3536:31)
    at Object.fireWith [as resolveWith] (jquery.js:3666:7)
```

### Server configuration
**Operating system**: Docker image (Ubuntu)
**Web server:** Apache
**Database:** SQLite
**Nextcloud version:** 28 master
**Where did you install Nextcloud from:** Docker dev image
**List of activated apps:**

```
Enabled:
  - activity: 2.20.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.28.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 1.23.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - forms: 3.3.1
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.2
  - provisioning_api: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - text: 3.9.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - testing: 1.18.0
  - user_ldap: 1.18.0
```

#### Browser log
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ script.js:1
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ feedSettings.js:2
session-heartbeat.js:103 session heartbeat polling started
snap.js:143 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
addEvent @ snap.js:143
(anonym) @ snap.js:250
listen @ snap.js:249
e.exports @ snap.js:512
Ue @ init.js:134
(anonym) @ main.js:41
snap.js:143 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
addEvent @ snap.js:143
(anonym) @ snap.js:253
listen @ snap.js:252
e.exports @ snap.js:512
Ue @ init.js:134
(anonym) @ main.js:41
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ backgroundjobs.js:24
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ backgroundjobs.js:26
localhost/:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden" method=​"POST">​…​</form>​
ConsoleLogger.js:50 [DEBUG] unified-search: Unified Search initialized with the following providers {0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, app: 'unified-search', uid: 'admin', level: 0}
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 Clipboard is deprecated: please ship your own, this will be removed in Nextcloud 20
In @ globals.js:59
get @ globals.js:90
(anonym) @ feedSettings.js:2
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
init @ feedSettings.js:2
(anonym) @ feedSettings.js:2
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
init @ feedSettings.js:2
(anonym) @ feedSettings.js:2
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
ConsoleLogger.js:50 [DEBUG] core: this browser is officially supported ! 🚀 {app: 'core', uid: 'admin', level: 0}
globals.js:59 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
In @ globals.js:59
get @ globals.js:90
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
util.js:127 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:127
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
util.js:127 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:127
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
In @ globals.js:59
get @ globals.js:90
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
util.js:127 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:127
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
In @ globals.js:59
get @ globals.js:90
makeSureDateGroupExists @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
richObjectStringParser.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'userLocal')
    at Object.parseParameter (richObjectStringParser.js:1:1076)
    at richObjectStringParser.js:1:278
    at Function.Ge (each.js:14:7)
    at Object.parseMessage (richObjectStringParser.js:1:192)
    at Object.addActivity (script.js:1:4262)
    at Object.appendActivityToContainer (script.js:1:3435)
    at Object.handleActivitiesCallback (script.js:1:2755)
    at Object.success (script.js:1:2330)
    at l (jquery.js:3536:31)
    at Object.fireWith [as resolveWith] (jquery.js:3666:7)
parseParameter @ richObjectStringParser.js:1
(anonym) @ richObjectStringParser.js:1
Ge @ each.js:14
parseMessage @ richObjectStringParser.js:1
addActivity @ script.js:1
appendActivityToContainer @ script.js:1
handleActivitiesCallback @ script.js:1
success @ script.js:1
l @ jquery.js:3536
fireWith @ jquery.js:3666
k @ jquery.js:9878
(anonym) @ jquery.js:10139
load (async)
send @ jquery.js:10158
ajax @ jquery.js:9772
(anonym) @ jquery-migrate.min.js:2
e.<computed> @ jquery-migrate.min.js:2
loadMoreActivities @ script.js:1
prefill @ script.js:1
setFilter @ script.js:1
(anonym) @ script.js:1
u @ jquery.js:3802
c @ jquery.js:3870
setTimeout (async)
(anonym) @ jquery.js:3908
l @ jquery.js:3536
fireWith @ jquery.js:3666
fire @ jquery.js:3674
l @ jquery.js:3536
fireWith @ jquery.js:3666
ready @ jquery.js:4146
setTimeout (async)
(anonym) @ jquery.js:4167
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
64265 @ NcHeaderMenu.js:2
r @ bootstrap:19
(anonym) @ core-main.js:2
r.O @ chunk loaded:25
(anonym) @ core-main.js:2
(anonym) @ core-main.js:2
[Violation] 'setInterval' handler took 51ms

```

**Comment by joshtrichards** [comment] 2024-08-07 20:24
Duplicate of #1196 
Not a problem today.

**Closed by joshtrichards** 2024-08-07 20:24 UTC
Labels: bug, 0. Needs triage, regression
