### ISSUE TITLE
OC\Group\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given

### ISSUE THREAD

**Issue by nblock** [nextcloud/activity#1537] opened 2024-01-24 19:36 UTC
### Steps to reproduce
1. Go to activity app
2. Enable RSS Feed
3. Request generated link via feed reader/curl

### Expected behaviour
A working RSS feed with recent activities

### Actual behaviour
HTTP/500 server error with `OC\Group\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given`

### Server configuration
**Operating system**: Ubuntu 22.04
**Web server:** Apache/2.4.52
**Database:** 8.0.35-0ubuntu0.22.04.1
**PHP version:** 8.1+92
**Nextcloud version:** 28.0.1.1
**Where did you install Nextcloud from:** tar.gz

**List of activated apps:**
  - activity: 2.20.0                        
  - admin_audit: 1.18.0                 
  - bookmarks: 13.1.3                
  - bruteforcesettings: 2.8.0              
  - calendar: 4.6.4                              
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0                    
  - contacts: 5.5.1                        
  - contactsinteraction: 1.9.0
  - dav: 1.29.1          
  - deck: 1.12.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_automatedtagging: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_retention: 1.17.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - flow_notifications: 1.8.0
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - lookup_server_connector: 1.16.0
  - news: 24.0.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tables: 0.6.6
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_retention: 1.11.0
  - viewer: 2.2.0
  - workflow_script: 1.13.0
  - workflowengine: 2.10.0

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** curl

#### Nextcloud log (data/nextcloud.log)
```json
{
  "reqId": "9sefX8LMpcI9ZwHVfJKo",
  "level": 3,
  "time": "2024-01-24T06:36:33+00:00",
  "remoteAddr": "11.22.33.444",
  "user": "--",
  "app": "index",
  "method": "GET",
  "url": "/index.php/apps/activity/rss.php?token=RANDOM_TOKEN",
  "message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php on line 374 in file '/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php' line 391",
  "userAgent": "A feed reader",
  "version": "28.0.1.1",
  "exception": {
    "Exception": "Exception",
    "Message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php on line 374 in file '/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php' line 391",
    "Code": 0,
    "Trace": [
      {
        "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/srv/nextcloud/nextcloud-28.0.1/lib/base.php",
        "line": 1069,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/srv/nextcloud/nextcloud-28.0.1/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/srv/nextcloud/nextcloud-28.0.1/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 169,
    "Previous": {
      "Exception": "TypeError",
      "Message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php on line 374",
      "Code": 0,
      "Trace": [
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php",
          "line": 374,
          "function": "getUserIdGroupIds",
          "class": "OC\\Group\\Manager",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps_custom/deck/lib/Service/PermissionService.php",
          "line": 234,
          "function": "isInGroup",
          "class": "OC\\Group\\Manager",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps_custom/deck/lib/Service/PermissionService.php",
          "line": 115,
          "function": "userCan",
          "class": "OCA\\Deck\\Service\\PermissionService",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps_custom/deck/lib/Service/PermissionService.php",
          "line": 160,
          "function": "getPermissions",
          "class": "OCA\\Deck\\Service\\PermissionService",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps_custom/deck/lib/Activity/ActivityManager.php",
          "line": 571,
          "function": "checkPermission",
          "class": "OCA\\Deck\\Service\\PermissionService",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps_custom/deck/lib/Activity/DeckProvider.php",
          "line": 131,
          "function": "canSeeCardActivity",
          "class": "OCA\\Deck\\Activity\\ActivityManager",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps/activity/lib/GroupHelper.php",
          "line": 72,
          "function": "parse",
          "class": "OCA\\Deck\\Activity\\DeckProvider",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps/activity/lib/Data.php",
          "line": 248,
          "function": "addActivity",
          "class": "OCA\\Activity\\GroupHelper",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/apps/activity/lib/Controller/FeedController.php",
          "line": 75,
          "function": "get",
          "class": "OCA\\Activity\\Data",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 230,
          "function": "show",
          "class": "OCA\\Activity\\Controller\\FeedController",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 137,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/AppFramework/App.php",
          "line": 184,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/private/Route/Router.php",
          "line": 315,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/lib/base.php",
          "line": 1069,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/srv/nextcloud/nextcloud-28.0.1/index.php",
          "line": 39,
          "function": "handleRequest",
          "class": "OC",
          "type": "::"
        }
      ],
      "File": "/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php",
      "Line": 391
    },
    "message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php on line 374 in file '/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php' line 391",
    "exception": {},
    "CustomMessage": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php on line 374 in file '/srv/nextcloud/nextcloud-28.0.1/lib/private/Group/Manager.php' line 391"
  }
}
```

**Comment by joshtrichards** [comment] 2024-02-19 23:21
Duplicate of nextcloud/deck#5499 (and fixed in latest Deck)

**Closed by joshtrichards** 2024-02-19 23:21 UTC
