### ISSUE TITLE
Emptycontent view should show the proper icon

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#322] opened 2018-11-27 16:23 UTC
For Tasks or Calendar or Comments for example, instead of the generic Activity icon we could show the relevant app icon. Just like we do in the navigation bar.

**Comment by nickvergessen** [comment] 2019-03-07 08:25
Moving to 17 as this will be part of the Vue PR

**Comment by nickvergessen** [comment] 2019-11-19 19:53
Duplicate of #74

**Closed by nickvergessen** 2019-11-19 19:53 UTC
Labels: design, enhancement
