### ISSUE TITLE
Heading shows "Your activities" for all sections

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#1463] opened 2023-12-14 14:15 UTC
### Steps to reproduce
1. Navigate to different sections of the Activity app
2. Look at the heading (h1) text
3. It’s "Your activities" everywhere

### Expected behaviour
If we use a heading, it should be the same as the left navigation entry for each of the sections, right?

### Actual behaviour
![image](https://github.com/nextcloud/activity/assets/925062/39e7521b-4a2c-4be7-b0dc-956accde9888)

![image](https://github.com/nextcloud/activity/assets/925062/d60bc841-9a0f-4f55-9361-550533782dc5)

### Server configuration

Current on cloud.nc as well as on tech-preview

**Comment by JuliaKirschenheuter** [comment] 2024-01-12 13:09
duplicate of https://github.com/nextcloud/activity/issues/1464

**Closed** 2024-01-12 13:09 UTC
Labels: bug, 1. to develop
