### ISSUE TITLE
Analytics Version 5.1.0 last update crash

### ISSUE THREAD

**Issue by fabiorsodre** [nextcloud/activity#1852] opened 2024-11-28 00:27 UTC
**Erro**: Could not resolve OCA\Analytics\Datasource\LocalExcel! Class "OCA\Analytics\Datasource\LocalExcel" does not exist GET /index.php/apps/analytics/

**Comment by joshtrichards** [comment] 2024-12-14 23:07
This appears unrelated.to this app (Activity) and a duplicate of an Issue already open over in that app's repo: Rello/analytics#419

**Closed by joshtrichards** 2024-12-14 23:07 UTC
Labels: bug, 0. Needs triage
