### ISSUE TITLE
OCS API - fileid is sometimes a string and sometimes an integer

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#152] opened 2017-05-10 21:59 UTC
* create a folder
* query the OCS activity API `ocs/v2.php/apps/activity/api/v2/activity?format=json`:

```
curl http://192.168.99.100/server/ocs/v2.php/apps/activity/api/v2/activity\?format=json -u admin:password  -H "OCS-APIRequest: true" -s | json_pp
{
   "ocs" : {
      "data" : [
         {
            "icon" : "http://192.168.99.100/server/apps/files/img/add-color.svg",
            "type" : "file_created",
            "object_id" : 75,
            "subject_rich" : [
               "Sie haben {file} erstellt",
               {
                  "file" : {
                     "link" : "http://192.168.99.100/server/f/75",
                     "path" : "asd",
                     "type" : "file",
                     "name" : "asd",
                     "id" : "75"
                  }
               }
            ],
            "app" : "files",
            "activity_id" : 2,
            "subject" : "Sie haben asd erstellt",
            "object_name" : "/asd",
            "objects" : {
               "75" : "/asd"
            },
            "datetime" : "2017-05-10T21:55:12+00:00",
            "object_type" : "files",
            "user" : "admin",
            "message" : null,
            "message_rich" : [
               "",
               []
            ],
            "link" : "http://192.168.99.100/server/apps/files/?dir=/"
         }
      ],
      "meta" : {
         "message" : "OK",
         "statuscode" : 200,
         "status" : "ok"
      }
   }
}
```

* entry ocs > data > subject_rich > file> id: "75" (string)

Shouldn't this be an integer @nickvergessen ?

cc @aleister09

**Comment by nickvergessen** [comment] 2017-05-10 22:34
https://github.com/nextcloud/server/blob/master/lib/public/RichObjectStrings/Definitions.php#L233

Not really, all data is considered to be string, to be on the save side.
You also had it as an int somewhere?

**Comment by MorrisJobke** [comment] 2017-05-11 00:18
I thought it was. @aleister09 could you check that?

**Comment by aleister09** [comment] 2017-05-11 15:09
Right the id sometimes is int
````
"subject_rich": [
          "{file} descargado vía enlace público",
          {
            "file": {
              "type": "file",
              "id": 8275,
              "name": "clarobox-090517.apk",
              "path": "APK/clarobox-090517.apk",
              "link": "https://drake.weasel.rocks/f/8275"
            }
          }
        ],
````

**Comment by nickvergessen** [comment] 2017-05-12 07:19
Well not sure what the problem is? Just cast it to string or int as needed?

**Comment by nickvergessen** [comment] 2017-05-12 07:26
Also I'm not quite sure how this happens, because the value is casted to a string:
https://github.com/nextcloud/server/blob/54e39d4b93b36d38c5f46ef5de4711de48baa0af/apps/files_sharing/lib/Activity/Providers/Base.php#L138-L138

**Comment by aleister09** [comment] 2017-05-12 16:47
@nickvergessen I think it's just happen with public_links
Like this
````
{
        "activity_id": 2581,
        "app": "files_sharing",
        "type": "public_links",
        "user": "",
        "subject": "alex123.jpg descargado vía enlace público",
        "subject_rich": [
          "{file} descargado vía enlace público",
          {
            "file": {
              "type": "file",
              "id": 8750,
              "name": "alex123.jpg",
              "path": "alex123.jpg",
              "link": "https://drake.weasel.rocks/f/8750"
            }
          }
        ],
        "message": null,
        "message_rich": [
          "",
          []
        ],
        "object_type": "files",
        "object_id": 8750,
        "object_name": "/alex123.jpg",
        "objects": {
          "8750": "/alex123.jpg"
        },
        "link": "",
        "icon": "https://drake.weasel.rocks/core/img/actions/download.svg",
        "datetime": "2017-05-12T16:41:34+00:00"
      }
````
or this
````
{
        "activity_id": 2196,
        "app": "files_sharing",
        "type": "public_links",
        "user": "",
        "subject": "APK/clarobox-090517.apk descargado vía enlace público",
        "subject_rich": [
          "{file} descargado vía enlace público",
          {
            "file": {
              "type": "file",
              "id": 8275,
              "name": "clarobox-090517.apk",
              "path": "APK/clarobox-090517.apk",
              "link": "https://drake.weasel.rocks/f/8275"
            }
          }
        ],
        "message": null,
        "message_rich": [
          "",
          []
        ],
        "object_type": "files",
        "object_id": 8275,
        "object_name": "/APK/clarobox-090517.apk",
        "objects": {
          "8275": "/APK/clarobox-090517.apk"
        },
        "link": "",
        "icon": "https://drake.weasel.rocks/core/img/actions/download.svg",
        "datetime": "2017-05-09T20:35:21+00:00"
      }
````

**Comment by MorrisJobke** [comment] 2017-05-12 17:31
> Well not sure what the problem is? Just cast it to string or int as needed?

It's just an indicator that there is maybe different handling on the server that could cause bugs.

**Comment by nickvergessen** [comment] 2017-05-13 10:03
Well each app has to do this on their own, so yes there is different handling,
if "notifying" was all, I'm going to close this.

**Closed by nickvergessen** 2017-05-13 10:03 UTC
