### ISSUE TITLE
`occ files:scan` does not trigger emails

### ISSUE THREAD

**Issue by Blaok** [nextcloud/activity#387] opened 2019-08-15 03:02 UTC
My apologies for not using the issue template, but this is more like a question than an issue.

According to [this issue](https://github.com/Blaok/nextcloud-inotifyscan/issues/12), it seems that the updates made by `occ files:scan` command is not triggering emails from the activity app. I was wondering if it is intended. If so, what is the rationale?

Also, if this is not the best place to ask this question, please let me know.

**Comment by nickvergessen** [comment] 2020-03-10 12:08
Duplicate of #233

**Closed by nickvergessen** 2020-03-10 12:08 UTC
