### ISSUE TITLE
not working with group folders

### ISSUE THREAD

**Issue by andreasmalta** [nextcloud/activity#264] opened 2018-04-18 10:31 UTC
Steps to reproduce
1. enable "Group folders" app
2. create a group folder and set permissions to an existing group
3. create a files/folders, edit files etc.

Expected behaviour
I would like the users to be notified in the activity app or by email, like it works for shared folders

Actual behaviour
in the activity stream there are no records...

Server configuration
Operating system: Centos7

Web server: Apache

Database: MariaDB

PHP version: 7.1 (ius)

Nextcloud version: 13.0.1

Where did you install Nextcloud from: https://download.nextcloud.com

Signing status: No errors have been found.

List of activated apps:
Activity
Auditing / Logging
Brute-force settings
Collabora Online
Collaborative tags
Deleted files
Draw.io
External sites
File access control
File sharing
Group folders
Impersonate
Log Reader
Monitoring
Notifications
PDF viewer
Talk
Theming
Update notification
Versions
Video player
Zimbra Drive

**Comment by team-a2** [comment] 2018-06-19 07:05
Using nextcloud 13.0.4 (activity 2.6.1, group folders 1.2.0), other group members still do not receive any mail on changes inside the group folder. If you change something, you will receive a mail for your changes.

Would be nice, when everyone of the group gets informed, when there are changes within the group folder.

Thank You!

**Comment by jacestk** [comment] 2018-08-02 08:08
Yep This is a really missing function. I have created severals groups folders and only the user who has uploaded the file is receiving the notification... that's nasty.

**Comment by noresistence** [comment] 2019-03-05 09:57
I can confirm the issue for 15.0.5
Possibly related to https://github.com/nextcloud/activity/pull/190 which does not seem to be worked on in recent past

**Comment by schmidtadrian** [comment] 2019-03-06 13:42
this Feature would be awesome!

**Comment by tim-bo** [comment] 2019-03-08 16:34
> I can confirm the issue for 15.0.5
> Possibly related to #190 which does not seem to be worked on in recent past

i also can confirm the problem. NC15.0.5 with groupfolders 2.0.3

**Comment by joe-speedboat** [comment] 2019-03-28 09:41
I can confirm the problem. NC15.0.5 with groupfolders 2.0.4
Sorry guys, but this is a show stopper. you work in teams shared by group folders and the activity is not visible to the members of group folders.
I cant belive that this issue is open for about a year!?
How do you handle this with your team members out there???
Is there a workaround???
Thanks Chris

**Comment by vpert** [comment] 2019-03-28 11:22
tis can't be a "feature" this is a basic requirement when running a shared storage platform. Really bad no one is taking care on this.
Tom

**Comment by Fin3** [comment] 2019-04-06 06:55
We need this feature too!

**Comment by Mululu** [comment] 2019-07-16 03:38
Push!

We're ist zur Support Team?

**Comment by sscholl** [comment] 2019-08-17 20:16
nobody cares?

**Comment by nickvergessen** [comment] 2019-08-19 14:19
We do care, we are just out of ideas:
https://github.com/nextcloud/activity/pull/190

**Comment by izzetaydin83** [comment] 2019-10-30 07:59
Any progress about this issue ?

**Comment by izzetaydin83** [comment] 2019-10-30 11:13
Find a way to resolve issue:

mysql -u root -D <dbname> -e "select from_unixtime(timestamp),type,user,SUBSTR(SUBSTRING_INDEX(oc_ldap_user_mapping.ldap_dn,',',1),4) ,app,file,object_type from oc_activity LEFT join oc_ldap_user_mapping ON (oc_activity.user=oc_ldap_user_mapping.owncloud_name) where timestamp > $epoch"

where epoch is epochtime-86400 gives me result of daily activity

**Comment by hriekehof** [comment] 2020-01-02 10:06
hi. If the fix @izzetaydin83 does work is there a change that this can be implemented ?
A fix for this would be really awesome since an activity feed is something everyone expects nowadays from a file sharing platform :)

**Comment by DarkknightAK** [comment] 2020-01-07 22:56
If the issue is fixed, close it.

**Comment by kokotko1337** [comment] 2020-01-08 08:51
@DarkknightAK it is not fixed

**Comment by sammo2828** [comment] 2020-02-03 13:36
> Find a way to resolve issue:
> 
> mysql -u root -D -e "select from_unixtime(timestamp),type,user,SUBSTR(SUBSTRING_INDEX(oc_ldap_user_mapping.ldap_dn,',',1),4) ,app,file,object_type from oc_activity LEFT join oc_ldap_user_mapping ON (oc_activity.user=oc_ldap_user_mapping.owncloud_name) where timestamp > $epoch"
> 
> where epoch is epochtime-86400 gives me result of daily activity

This doesn't *resolve* the issue so please don't write as such as it misleads most people tryout out nextcloud!

It's a workaround for particular users with mysql root access, which is laughable at best 😃

**Comment by sammo2828** [comment] 2020-02-03 13:45
> We do care, we are just out of ideas:
> #190

This gives an idea:

https://github.com/nextcloud/groupfolders/issues/112#issuecomment-477551279

When group folders are shared, they do appear in **Activity**, but then the folder appears twice when browsing the *files list* (once as a group folder, and once as a share folder). Of course, having repeated folders show up in the *files list* is not nice.

So the idea is to automatically share the group folder with the users/groups with access, and automatically hide the shared folders from the *files list*.

**Closed** 2020-04-01 15:22 UTC
Labels: bug

**Comment by phonon112358** [comment] 2020-05-05 15:45
In the meantime, I have manually applied the changes proposed in https://github.com/nextcloud/activity/pull/190 to my NS 18 instance ... It works like a charm!!! @nickvergessen

**Comment by Mululu** [comment] 2020-05-05 16:34
> In the meantime, I have manually applied the changes proposed in #190 to my NS 18 instance ... It works like a charm!!! @nickvergessen @wiswedel

Can you briefly explain what you have to do to make this work?

**Comment by phonon112358** [comment] 2020-05-05 17:10
You only need to change the `/var/www/nextcloud/apps/activity/lib/FilesHooks.php` according to https://github.com/nextcloud/activity/pull/190/files#diff-dbc5f6ba450710b214d9d73b15c9f186 (I just copied the changed file from the pull request and overwrote the existing file).
The second file from the PR, you don't even need! ;) 

It was really simple...

**Comment by phonon112358** [comment] 2020-05-25 13:18
Unfortunately, my fix doesn't work anymore !!! 
I don't know why ..... :( 
I still use NC 18.0.4 and activity 2.11.0

**Comment by diemelone** [comment] 2021-04-27 06:49
> 
> 
> You only need to change the `/var/www/nextcloud/apps/activity/lib/FilesHooks.php` according to https://github.com/nextcloud/activity/pull/190/files#diff-dbc5f6ba450710b214d9d73b15c9f186 (I just copied the changed file from the pull request and overwrote the existing file).
> The second file from the PR, you don't even need! ;)
> 
> It was really simple...

@nickvergessen is that still the official fix? Because it does not work for me...

I have tried the other fix from you I found here https://github.com/nextcloud/activity/pull/190#issuecomment-597037739
Groupfolders now show up in the activity app but mails are not sent
For Activity 1.10.0 the fix was applied to line 234 in `lib/FilesHooks.php`
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/activity_configuration.html#activities-in-groupfolders

How to get activity mails for groupfolders?

**Comment by nickvergessen** [comment] 2021-04-27 07:13
We are not going to add a checkbox. The config with dedicated documentation page is the real solution.

**Comment by maeno14** [comment] 2025-01-23 16:42
This should work as intended it should be defaulted to show activity in group folders to the members of the group allowed to view the folder.
