### ISSUE TITLE
Feature Request: Link calendar event to the corresponding activity

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/activity#378] opened 2019-05-29 07:02 UTC
Hi,

first of all, great app, really useful to keep an eye at what's happening! We use the calender in NC quite extensively within the office and I was wondering if there is a possibility to link a calendar event to the corresponding activity.

**Example**
If person x adds an event it pops up in the timeline, but it's quite hard to figure out when they booked it. The most convenient would be to be able to click on the title of the event in the timeline and hop over to the calendar (new tab) to see the actual event and its date + all the information in it.

I don't know if that's possible, but it would be an amazing feature!

**Comment by nickvergessen** [comment] 2019-06-20 15:04
Duplicate of #170

**Closed by nickvergessen** 2019-06-20 15:04 UTC
