### ISSUE TITLE
Activity tab not working after upgrade to v18

### ISSUE THREAD

**Issue by quenenni** [nextcloud/activity#431] opened 2020-02-29 18:21 UTC
### Steps to reproduce
1. Upgrade from Debian Stretch to Buster
2. Upgrade Nc from 15 to 16 (all good)
3. Upgrade Nc from 16 to 17 (all good)
4. Upgrade Nc from 17 to 18 (all good except Activity)

### Expected behaviour
See the activities in the activity tab

### Actual behaviour
A spinning icon stays there and nothing happens
(Was working in v15, v16 & v17)

### Server configuration

**Operating system**:
Debian Buster 10.3

**Web server:**
nginx/1.14.2

**Database:**
Mariadb v10.3.22-MariaDB-0+deb10u1

**PHP version:**
v7.3.14-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)
v18.0.1

**Where did you install Nextcloud from:**
deb http://apt.jurisic.org/debian/ buster main contrib non-free

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.9
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.17
  - files_pdfviewer: 1.7.0
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - flowupload: 0.1.8
  - impersonate: 1.5.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ownpad: 0.6.14
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.4
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - deck
  - discoursesso
  - drawio
  - files_external
  - files_rightclick
  - firstrunwizard
  - logreader
  - mail
  - music
  - passman
  - polls
  - quota_warning
  - support
```

**Nextcloud configuration:**

```
{
    "system": {
        "trusted_domains": [
            "xxx.yyy.zzz"   <- this should be also SENSITIVE VALUE
        ],
        "activity_expire_days": 180,
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "auth.bruteforce.protection.enabled": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "hashingCost": 10,
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "integrity.check.disabled": true,
        "logfile": "\/var\/log\/nextcloud\/xxx.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Brussels",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpport": 25,
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "minimum.supported.desktop.version": "2.1.0",
        "mysql.utf8mb4": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_max_filesize_image": 5,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "60, 90",
        "updatechecker": true,
        "upgrade.disable-web": true,
        "version": "18.0.1.3",
        "versions_retention_obligation": "60, 90",
        "overwrite.cli.url": "https:\/\/xxx.yyy.zzz\/"  <- this should be also SENSITIVE VALUE
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 73.0.1 (64 bits)

**Operating system:**
Debian Stretch 9.11

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"9e2zAHpQKo4GEH7WSJvU","level":3,"time":"2020-02-29T19:10:49+01:00","remoteAddr":"xx.yy.zz.aa","user":"xxx","app":"no app in context","method":"GET","url|
":"/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0","message":{"Exception":"Exception","Message":"substr() expects parameter 3 to be int,|
 bool given","Code":0,"Trace":[{"file":"/home/nextcloud/instances/transquinquennal/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFra|
mework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Activity\\Controller\\APIv2"},"getFilter"]},{"file":"/home/nextcloud/instances/transquinquennal/lib/priv|
ate/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["APIv2Controller","getFilter",{"__class_|
_":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"filter":"all","_route":"ocs.activity.APIv2.getFilter"}]},{"function":"__invoke","class":"OC\\AppFramework\\Rou|
ting\\RouteActionHandler","type":"->","args":[{"filter":"all","_route":"ocs.activity.APIv2.getFilter"}]},{"file":"/home/nextcloud/instances/transquinquennal/lib/private/|
Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"filter":"all","_route":"ocs.activity.API|
v2.getFilter"}]},{"file":"/home/nextcloud/instances/transquinquennal/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/ap|
ps/activity/api/v2/activity/all"]},{"file":"/home/nextcloud/instances/transquinquennal/ocs/v2.php","line":24,"args":["/home/nextcloud/instances/transquinquennal/ocs/v1.p|
hp"],"function":"require_once"}],"File":"/home/nextcloud/instances/transquinquennal/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"Typ|
eError","Message":"substr() expects parameter 3 to be int, bool given","Code":0,"Trace":[{"file":"/home/nextcloud/instances/transquinquennal/lib/private/Files/Type/Detec|
tion.php","line":377,"function":"substr","args":["mindmap",0,false]},{"file":"/home/nextcloud/instances/transquinquennal/apps/activity/lib/Controller/APIv2.php","line":4|
08,"function":"mimeTypeIcon","class":"OC\\Files\\Type\\Detection","type":"->","args":["mindmap"]},{"file":"/home/nextcloud/instances/transquinquennal/apps/activity/lib/C|
ontroller/APIv2.php","line":388,"function":"getPreviewPathFromMimeType","class":"OCA\\Activity\\Controller\\APIv2","type":"->","args":["application/km"]},{"file":"/home/|
nextcloud/instances/transquinquennal/apps/activity/lib/Controller/APIv2.php","line":304,"function":"getPreview","class":"OCA\\Activity\\Controller\\APIv2","type":"->","a|
rgs":["xxx",749629,"/hgk.km"]},{"file":"/home/nextcloud/instances/transquinquennal/apps/activity/lib/Controller/APIv2.php","line":209,"function":"get","class":"OCA\|
\Activity\\Controller\\APIv2","type":"->","args":["all",0,50,true,"",0,"desc"]},{"file":"/home/nextcloud/instances/transquinquennal/lib/private/AppFramework/Http/Dispatc|
her.php","line":170,"function":"getFilter","class":"OCA\\Activity\\Controller\\APIv2","type":"->","args":["all",0,50,true,"",0,"desc"]},{"file":"/home/nextcloud/instance|
s/transquinquennal/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args"
:[{"__class__":"OCA\\Activity\\Controller\\APIv2"},"getFilter"]},{"file":"/home/nextcloud/instances/transquinquennal/lib/private/AppFramework/App.php","line":125,"functi
on":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Activity\\Controller\\APIv2"},"getFilter"]},{"file":"/home/nextcloud/i
nstances/transquinquennal/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["APIv2
Controller","getFilter",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"filter":"all","_route":"ocs.activity.APIv2.getFilter"}]},{"function":"__invo
ke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"filter":"all","_route":"ocs.activity.APIv2.getFilter"}]},{"file":"/home/nextcloud/insta
nces/transquinquennal/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"filter
":"all","_route":"ocs.activity.APIv2.getFilter"}]},{"file":"/home/nextcloud/instances/transquinquennal/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Route
r","type":"->","args":["/ocsapp/apps/activity/api/v2/activity/all"]},{"file":"/home/nextcloud/instances/transquinquennal/ocs/v2.php","line":24,"args":["/home/nextcloud/i
nstances/transquinquennal/ocs/v1.php"],"function":"require_once"}],"File":"/home/nextcloud/instances/transquinquennal/lib/private/Files/Type/Detection.php","Line":377},"
CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}
```

#### Browser log
```
a) The javascript console log

Content Security Policy: La directive « child-src » est obsolète. Veuillez utiliser la directive « worker-src » pour contrôler des workers ou la directive « frame-src » pour contrôler des images.
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». addStylesClient.js:220:17
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 globals.js:66:15
Clipboard is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15

b) The network log

All requests returned a 200 except one that returned a 404:
GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0 HTTP/1.1

```

**Comment by chrisjq** [comment] 2020-03-04 10:08
I have the same issue

**Comment by nickvergessen** [comment] 2020-03-10 11:49
It seems to be caused by an invalid mimetype map entry (`mindmap` is used for `application/mk`).
Did you specify this yourself? Or install a mindmap app or something?

**Comment by quenenni** [comment] 2020-03-10 16:35
@nickvergessen Good catch. Thanks.

Indeed mindmap is installed and active, but I don't know why it isn't in the list of apps generated by the command occ (sudo -u www-data php occ app:list)

I tried again and again, mindmap is not listed.

I deactivated it and now Activity is working well.

So.. Does it mean mindmap can't be used in 18 atm? Or is it a problem from core project?

**Comment by nickvergessen** [comment] 2020-03-10 16:45
Do you have a link to the app for me?

**Comment by quenenni** [comment] 2020-03-10 16:48
Better, I created a link between mindmap repo and this ticket.

I tested with the last version of mindmap (0.0.17)

**Comment by quenenni** [comment] 2020-03-10 16:54
Another post with the same problem it seems:
https://github.com/ACTom/files_mindmap/issues/84

**Comment by nickvergessen** [comment] 2020-03-11 08:01
Fixed by https://github.com/ACTom/files_mindmap/commit/ad802f6186f9f531de927eb82f49818492e3dc10

**Closed by nickvergessen** 2020-03-11 08:01 UTC
Labels: 0. Needs triage, needs info
