### ISSUE TITLE
No activity for files added directly to data directory via scp

### ISSUE THREAD

**Issue by nlrivera** [nextcloud/activity#762] opened 2022-03-15 20:39 UTC
### Steps to reproduce
1. scp a file into the data directory as root that nextcloud is using
2. chown the file to set user and group to www-data
3. force nextcloud to scan for new files

### Expected behaviour
Activity stream should show that the file was created at X time

### Actual behaviour
Activity stream states that there is No Activity yet

### Server configuration

**Operating system**: Ubuntu 20.04.1

**Web server:** apache2 2.4.52

**Database:** sqlite3

**PHP version:** 8.0.16

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:** Docker pull

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here. - No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_automatedtagging: 1.13.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "23.0.2.1",
        "overwrite.cli.url": "http:\/\/127.0.0.1:8080",
        "installed": true,
        "activity_use_cached_mountpoints": true
    }
}


```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Firefox 98.0 (64-bit)

**Operating system:** Ubuntu 20.04.1

**Comment by joshtrichards** [comment] 2024-08-06 17:47
Duplicate of #233

**Closed by joshtrichards** 2024-08-06 17:47 UTC
Labels: enhancement
